// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: article.proto

/*
Package blog is a generated protocol buffer package.

It is generated from these files:
	article.proto

It has these top-level messages:
	EmptyRequest
	Article
	GetAllArticleResponse
*/
package blog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Blog service

type BlogClient interface {
	GetAllArticle(ctx context.Context, in *EmptyRequest, opts ...client.CallOption) (*GetAllArticleResponse, error)
}

type blogClient struct {
	c           client.Client
	serviceName string
}

func NewBlogClient(serviceName string, c client.Client) BlogClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "blog"
	}
	return &blogClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *blogClient) GetAllArticle(ctx context.Context, in *EmptyRequest, opts ...client.CallOption) (*GetAllArticleResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Blog.GetAllArticle", in)
	out := new(GetAllArticleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Blog service

type BlogHandler interface {
	GetAllArticle(context.Context, *EmptyRequest, *GetAllArticleResponse) error
}

func RegisterBlogHandler(s server.Server, hdlr BlogHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Blog{hdlr}, opts...))
}

type Blog struct {
	BlogHandler
}

func (h *Blog) GetAllArticle(ctx context.Context, in *EmptyRequest, out *GetAllArticleResponse) error {
	return h.BlogHandler.GetAllArticle(ctx, in, out)
}
