// This file was generated by github.com/vektah/gqlgen, DO NOT EDIT

package graph

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User User   `json:"user"`
}
type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
