// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: compiler.proto

/*
Package compiler is a generated protocol buffer package.

It is generated from these files:
	compiler.proto

It has these top-level messages:
	CompileRequest
	CompileResponse
*/
package compiler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Compile service

type CompileClient interface {
	Run(ctx context.Context, in *CompileRequest, opts ...client.CallOption) (*CompileResponse, error)
}

type compileClient struct {
	c           client.Client
	serviceName string
}

func NewCompileClient(serviceName string, c client.Client) CompileClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "compile"
	}
	return &compileClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *compileClient) Run(ctx context.Context, in *CompileRequest, opts ...client.CallOption) (*CompileResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Compile.Run", in)
	out := new(CompileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Compile service

type CompileHandler interface {
	Run(context.Context, *CompileRequest, *CompileResponse) error
}

func RegisterCompileHandler(s server.Server, hdlr CompileHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Compile{hdlr}, opts...))
}

type Compile struct {
	CompileHandler
}

func (h *Compile) Run(ctx context.Context, in *CompileRequest, out *CompileResponse) error {
	return h.CompileHandler.Run(ctx, in, out)
}
